[package]
name = "version_analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
time = { version = "0.3", features = ["parsing", "serde", "macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
